import type { EnglishBeginnerArticle } from "@/lib/english-beginner-content";

export const englishMovementBatchSixArticles = [
  {
    slug: "screeps-move-fatigue-body-ratio",
    path: "/en/blog/screeps-move-fatigue-body-ratio",
    chinesePath: "/blog/screeps-move-fatigue-body-ratio",
    title: "Screeps MOVE Parts: Fatigue, Terrain, and Body Ratios",
    headline: "How to Calculate Screeps Creep Movement Speed",
    description:
      "Calculate unboosted Creep movement from MOVE recovery, loaded body weight, road, plain, and swamp costs; account for empty CARRY parts; and separate a static body estimate from live multi-tick movement proof.",
    category: "MOVEMENT · FATIGUE AND BODY DESIGN",
    publishedAt: "2026-07-25",
    publishedLabel: "July 25, 2026",
    readingTime: "16 min read",
    breadcrumbLabel: "MOVE Parts and Fatigue",
    tags: ["Screeps", "MOVE", "Fatigue", "Creep Body", "Terrain"],
    keywords: [
      "Screeps MOVE parts ratio",
      "Screeps fatigue calculation",
      "Creep movement speed",
      "Screeps road plain swamp cost",
      "empty CARRY fatigue",
    ],
    primaryKeyword: "Screeps MOVE parts ratio",
    searchIntent: "Calculate Creep movement speed and choose an unboosted MOVE ratio",
    finalScore: 98,
    verification: [
      ["Chinese source article", "Reviewed in full"],
      ["Official docs", "Checked — movement weight, terrain costs, empty CARRY and MOVE recovery"],
      ["Formula boundary", "Unboosted MOVE only; boosts and pull mechanics are excluded"],
      ["Source correction", "The estimator accepts the terrain being entered instead of treating the current tile as proof of the next step cost"],
      ["JavaScript syntax", "Passed"],
      ["Offline calculation review", "Passed — empty and loaded CARRY, roads, plains, swamps, invalid input and damaged MOVE capacity"],
      ["Screeps Console test", "Pending"],
      ["Live multi-tick movement test", "Pending"],
      ["Last verified", "July 25, 2026"],
    ],
    toc: [
      ["quick-answer", "Quick answer"],
      ["movement-rules", "The four movement rules"],
      ["weight", "Count movement weight correctly"],
      ["formula", "Calculate ticks per step"],
      ["examples", "Road, plain, and swamp examples"],
      ["carry", "Why empty CARRY parts change the result"],
      ["calculator", "Complete unboosted movement calculator"],
      ["body-ratios", "Practical body ratios"],
      ["damage", "Why damage can slow a Creep"],
      ["source-correction", "Terrain-sampling correction"],
      ["debugging", "Debugging checklist"],
      ["scope", "Scope and next steps"],
      ["faq", "FAQ"],
      ["official-docs", "Official documentation"],
    ],
    faq: [
      [
        "How many MOVE parts does a Creep need on plains?",
        "For maximum unboosted speed on plains, one active MOVE part can support one fatigue-generating body part. Empty CARRY parts do not count as weight until resources occupy them.",
      ],
      [
        "Why does a hauler move faster when empty?",
        "Empty CARRY parts do not generate movement fatigue. As resources fill CARRY capacity, more CARRY parts become loaded and contribute weight.",
      ],
      [
        "Does one movement calculation prove the real speed?",
        "No. Traffic, existing fatigue, changing terrain, pull mechanics, boosts, damage, and overwritten movement orders require multi-tick observation.",
      ],
      [
        "Can a Creep move faster than one tile per tick?",
        "No. Extra MOVE capacity can prevent fatigue, but ordinary Creep movement is still limited to one tile per tick.",
      ],
    ],
    previous: {
      href: "/en/blog/screeps-err-no-path",
      label: "Previous movement guide",
      title: "Debug ERR_NO_PATH",
    },
    next: {
      href: "/en/blog/screeps-roomposition-distance",
      label: "Next position guide",
      title: "Choose the Correct Distance Method",
    },
    articleHtml: String.raw`
<h2 id="quick-answer">Quick answer</h2>
<p>An unboosted Creep's movement interval depends on two values: the fatigue generated by the body weight on the tile being entered, and the fatigue removed by active MOVE parts. Roads cost 1 fatigue per weight part, plains cost 2, and swamps cost 10. Each active unboosted MOVE part removes 2 fatigue per tick. Empty CARRY parts do not add weight.</p>

<h2 id="movement-rules">The four movement rules</h2>
<ul>
<li>Every non-MOVE weight part generates fatigue when the Creep moves.</li>
<li>A road uses cost 1, a plain uses cost 2, and a swamp uses cost 10.</li>
<li>Each active unboosted MOVE part removes 2 fatigue per tick.</li>
<li>A Creep with positive fatigue cannot submit ordinary movement successfully.</li>
</ul>
<p>The maximum normal speed is one tile per tick. Extra MOVE capacity beyond the amount required for zero carried fatigue does not create two-tile movement.</p>

<h2 id="weight">Count movement weight correctly</h2>
<p>For an unboosted estimate, weight contains every non-MOVE body part except empty CARRY capacity. A loaded CARRY part counts when some resource occupies its 50-capacity segment.</p>
<pre><code class="language-javascript">function countLoadedCarryParts(
  activeCarryParts,
  usedCapacity
) {
  if (
    !Number.isInteger(activeCarryParts)
    || activeCarryParts < 0
    || !Number.isFinite(usedCapacity)
    || usedCapacity <= 0
  ) {
    return 0;
  }

  return Math.min(
    activeCarryParts,
    Math.ceil(usedCapacity / CARRY_CAPACITY)
  );
}</code></pre>
<p>Examples for three unboosted CARRY parts:</p>
<div class="table-scroll"><table>
<thead><tr><th>Used capacity</th><th>Loaded CARRY parts</th></tr></thead>
<tbody>
<tr><td>0</td><td>0</td></tr>
<tr><td>1–50</td><td>1</td></tr>
<tr><td>51–100</td><td>2</td></tr>
<tr><td>101–150</td><td>3</td></tr>
</tbody></table></div>

<h2 id="formula">Calculate ticks per step</h2>
<pre><code class="language-text">fatigue generated = weight parts × terrain cost
fatigue removed per tick = active MOVE parts × 2
estimated ticks per step = ceil(
  fatigue generated / fatigue removed per tick
)</code></pre>
<p>The result is never less than one tick. A Creep must have at least one active MOVE part to move under its own power.</p>
<pre><code class="language-javascript">const TERRAIN_COST = {
  road: 1,
  plain: 2,
  swamp: 10
};

function estimateTicksPerStep(input) {
  const {
    activeMoveParts,
    weightParts,
    terrain
  } = input;
  const terrainCost = TERRAIN_COST[terrain];

  if (
    !Number.isInteger(activeMoveParts)
    || activeMoveParts <= 0
    || !Number.isInteger(weightParts)
    || weightParts < 0
    || !Number.isInteger(terrainCost)
  ) {
    return {
      movable: false,
      reason: 'invalid-input'
    };
  }

  const fatigueGenerated = weightParts * terrainCost;
  const fatigueRemovedPerTick = activeMoveParts * 2;

  return {
    movable: true,
    reason: 'estimated',
    fatigueGenerated,
    fatigueRemovedPerTick,
    ticksPerStep: Math.max(
      1,
      Math.ceil(
        fatigueGenerated / fatigueRemovedPerTick
      )
    )
  };
}</code></pre>

<h2 id="examples">Road, plain, and swamp examples</h2>
<p>Consider a fully loaded <code>[WORK, CARRY, MOVE]</code> Creep. It has two weight parts and one MOVE part.</p>
<div class="table-scroll"><table>
<thead><tr><th>Terrain</th><th>Generated</th><th>Removed per tick</th><th>Estimated interval</th></tr></thead>
<tbody>
<tr><td>Road</td><td>2 × 1 = 2</td><td>2</td><td>1 tick per step</td></tr>
<tr><td>Plain</td><td>2 × 2 = 4</td><td>2</td><td>2 ticks per step</td></tr>
<tr><td>Swamp</td><td>2 × 10 = 20</td><td>2</td><td>10 ticks per step</td></tr>
</tbody></table></div>
<p>Adding a second MOVE part changes the plain result to one tile per tick, but the same body still needs several ticks per swamp step.</p>

<h2 id="carry">Why empty CARRY parts change the result</h2>
<p><code>[CARRY, CARRY, MOVE]</code> has zero movement weight while empty, one weight part with up to 50 resources, and two weight parts above 50 resources. A hauler can therefore travel outward quickly and return more slowly when loaded.</p>
<p>Do not count every CARRY part automatically. Also do not assume all resources are energy; <code>creep.store.getUsedCapacity()</code> counts the complete load.</p>

<h2 id="calculator">Complete unboosted movement calculator</h2>
<p><strong>State impact:</strong> this diagnostic reads the body and Store and returns an estimate. It does not move the Creep or write Memory.</p>
<pre><code class="language-javascript">const TERRAIN_COST = {
  road: 1,
  plain: 2,
  swamp: 10
};

function countLoadedCarryParts(creep) {
  const usedCapacity =
    creep.store.getUsedCapacity() ?? 0;
  const activeCarryParts =
    creep.getActiveBodyparts(CARRY);

  if (usedCapacity <= 0) {
    return 0;
  }

  return Math.min(
    activeCarryParts,
    Math.ceil(usedCapacity / CARRY_CAPACITY)
  );
}

function countWeightParts(creep) {
  const activeOtherParts = creep.body.filter(
    part =>
      part.hits > 0
      && part.type !== MOVE
      && part.type !== CARRY
  ).length;

  return activeOtherParts
    + countLoadedCarryParts(creep);
}

function estimateCreepMovement(creep, terrain) {
  if (!creep || creep.spawning) {
    return {
      status: 'creep-unavailable'
    };
  }

  const terrainCost = TERRAIN_COST[terrain];
  const activeMoveParts =
    creep.getActiveBodyparts(MOVE);
  const weightParts = countWeightParts(creep);

  if (!Number.isInteger(terrainCost)) {
    return {
      status: 'terrain-invalid'
    };
  }

  if (activeMoveParts <= 0) {
    return {
      status: 'no-active-move-part',
      activeMoveParts,
      weightParts,
      currentFatigue: creep.fatigue
    };
  }

  const fatigueGenerated =
    weightParts * terrainCost;
  const fatigueRemovedPerTick =
    activeMoveParts * 2;

  return {
    status: 'movement-estimated',
    terrain,
    activeMoveParts,
    weightParts,
    currentFatigue: creep.fatigue,
    fatigueGenerated,
    fatigueRemovedPerTick,
    estimatedTicksPerStep: Math.max(
      1,
      Math.ceil(
        fatigueGenerated / fatigueRemovedPerTick
      )
    )
  };
}

module.exports.loop = function () {
  const creep = Game.creeps.Hauler1;

  if (!creep || Game.time % 25 !== 0) {
    return;
  }

  console.log(JSON.stringify({
    type: 'movement-estimate',
    creepName: creep.name,
    ...estimateCreepMovement(creep, 'plain')
  }));
};</code></pre>
<p>The terrain argument describes the route segment being evaluated. Do not label one current-tile snapshot as a measured route speed.</p>

<h2 id="body-ratios">Practical body ratios</h2>
<div class="table-scroll"><table>
<thead><tr><th>Expected terrain</th><th>Unboosted maximum-speed target</th></tr></thead>
<tbody>
<tr><td>Mostly roads</td><td>1 MOVE per 2 loaded weight parts</td></tr>
<tr><td>Mostly plains</td><td>1 MOVE per 1 loaded weight part</td></tr>
<tr><td>Mostly swamps</td><td>5 MOVE per 1 loaded weight part</td></tr>
</tbody></table></div>
<p>Swamp-speed bodies are often impractical. Roads, route changes, reduced payload, or MOVE boosts may be cheaper than adding enough MOVE parts for one-tile-per-tick swamp travel.</p>

<h2 id="damage">Why damage can slow a Creep</h2>
<p>Use <code>getActiveBodyparts(MOVE)</code>, not the original body array length. A MOVE part at zero hits no longer contributes movement recovery. The same body can therefore move normally before combat and accumulate fatigue afterward.</p>
<p>Live diagnosis should record active MOVE parts, Store usage, fatigue, terrain, and position over multiple ticks.</p>

<h2 id="source-correction">Terrain-sampling correction</h2>
<p>The Chinese source's complete diagnostic read the Creep's current tile and used that value as the movement estimate. A route can enter a different terrain type on the next step. This English version requires the terrain being evaluated as an explicit input and labels the result as an estimate rather than a measured next-step fact.</p>

<h2 id="debugging">Debugging checklist</h2>
<ul>
<li>Use active MOVE parts, not the original count.</li>
<li>Count only loaded CARRY capacity as weight.</li>
<li>Use costs 1, 2, and 10 for road, plain, and swamp.</li>
<li>Keep unboosted and boosted formulas separate.</li>
<li>Include current fatigue in live logs.</li>
<li>Evaluate the terrain of the route segment, not only the current tile.</li>
<li>Do not confuse a static estimate with multi-tick proof.</li>
<li>Check traffic and overwritten movement orders before adding MOVE parts.</li>
</ul>

<h2 id="scope">Scope and next steps</h2>
<p>This guide excludes MOVE boosts, pull chains, Power Creeps, traffic reservations, mixed-terrain route statistics, and live server timing. Continue with <a href="/en/blog/screeps-roomposition-distance">RoomPosition distance methods</a> before using range as a path estimate.</p>

<h2 id="faq">Frequently asked questions</h2>
<h3>What is the plain-terrain ratio?</h3>
<p>One active unboosted MOVE part per loaded weight part supports maximum normal speed on plains.</p>
<h3>Why is an empty hauler faster?</h3>
<p>Empty CARRY parts do not generate fatigue.</p>
<h3>Does more MOVE exceed one tile per tick?</h3>
<p>No. It can remove fatigue faster, but ordinary movement remains capped at one tile per tick.</p>
<h3>Is the formula a live test?</h3>
<p>No. Observe several ticks to include traffic, fatigue history, terrain changes, and command conflicts.</p>

<h2 id="official-docs">Official documentation</h2>
<ul>
<li><a href="https://docs.screeps.com/creeps.html#Movement" rel="nofollow">Screeps Documentation: Movement</a></li>
<li><a href="https://docs.screeps.com/api/#Creep.fatigue" rel="nofollow">API Reference: Creep.fatigue</a></li>
<li><a href="https://docs.screeps.com/api/#Creep.getActiveBodyparts" rel="nofollow">API Reference: Creep.getActiveBodyparts()</a></li>
<li><a href="https://docs.screeps.com/api/#Store.getUsedCapacity" rel="nofollow">API Reference: Store.getUsedCapacity()</a></li>
</ul>`,
  },
  {
    slug: "screeps-roomposition-distance",
    path: "/en/blog/screeps-roomposition-distance",
    chinesePath: "/blog/screeps-roomposition-distance",
    title: "Screeps RoomPosition Distance: Range vs Path",
    headline: "Which Screeps RoomPosition Distance Method Should You Use?",
    description:
      "Choose between getRangeTo(), inRangeTo(), isNearTo(), isEqualTo(), findClosestByRange(), findClosestByPath(), and findInRange() without confusing linear range with route reachability.",
    category: "MOVEMENT · ROOMPOSITION DISTANCE",
    publishedAt: "2026-07-25",
    publishedLabel: "July 25, 2026",
    readingTime: "15 min read",
    breadcrumbLabel: "RoomPosition Distance",
    tags: ["Screeps", "RoomPosition", "Range", "Pathfinding", "Creep API"],
    keywords: [
      "Screeps RoomPosition distance",
      "getRangeTo vs findClosestByPath",
      "Screeps isNearTo same tile",
      "findClosestByRange Screeps",
      "Screeps action range",
    ],
    primaryKeyword: "Screeps RoomPosition distance",
    searchIntent: "Select the correct range, equality, adjacency, filtering, or path method",
    finalScore: 98,
    verification: [
      ["Chinese source article", "Reviewed in full"],
      ["Official docs", "Checked — RoomPosition range, equality, adjacency and closest-target methods"],
      ["Room boundary", "Same-room linear comparison is separated from cross-room routing"],
      ["Semantic boundary", "isNearTo() includes the same tile because it equals inRangeTo(target, 1)"],
      ["JavaScript syntax", "Passed"],
      ["Offline relation review", "Passed — equal, adjacent, diagonal, range 3, cross-room and target-selection states"],
      ["Screeps Console test", "Pending"],
      ["Live path and target-selection test", "Pending"],
      ["Last verified", "July 25, 2026"],
    ],
    toc: [
      ["quick-answer", "Quick answer"],
      ["two-distances", "Linear range and path distance"],
      ["range-methods", "getRangeTo() and inRangeTo()"],
      ["near-equal", "isNearTo() and isEqualTo()"],
      ["closest", "Closest by range or path"],
      ["find-in-range", "Filter candidates with findInRange()"],
      ["cross-room", "Do not compare local coordinates across rooms"],
      ["relation-helper", "Complete same-room relation helper"],
      ["action-example", "Use the required action range"],
      ["reachability", "Range does not prove reachability"],
      ["debugging", "Debugging checklist"],
      ["scope", "Scope and next steps"],
      ["faq", "FAQ"],
      ["official-docs", "Official documentation"],
    ],
    faq: [
      [
        "Does getRangeTo() consider walls and structures?",
        "No. It returns linear grid range. Use pathfinding when you need to know how a Creep can actually reach a target.",
      ],
      [
        "Does isNearTo() exclude the same tile?",
        "No. The API defines it as inRangeTo(target, 1), so range 0 also satisfies the test. Combine it with !isEqualTo() for strict adjacency between coordinate objects.",
      ],
      [
        "When should I use findClosestByRange()?",
        "Use it when linear proximity is the intended metric or as a cheap first-stage filter. It does not guarantee a usable path.",
      ],
      [
        "Can I compare x and y between different rooms?",
        "Not as a world-route distance. Check roomName first, then use map routing, PathFinder, or moveTo() for cross-room travel.",
      ],
    ],
    previous: {
      href: "/en/blog/screeps-move-fatigue-body-ratio",
      label: "Previous movement guide",
      title: "Calculate MOVE and Fatigue",
    },
    next: {
      href: "/en/blog/screeps-map-find-route",
      label: "Next routing guide",
      title: "Plan a Cross-Room Route",
    },
    articleHtml: String.raw`
<h2 id="quick-answer">Quick answer</h2>
<p>Use RoomPosition range methods to answer a coordinate question and path methods to answer a travel question. <code>getRangeTo()</code>, <code>inRangeTo()</code>, <code>isNearTo()</code>, <code>isEqualTo()</code>, <code>findClosestByRange()</code>, and <code>findInRange()</code> do not prove that terrain and structures permit a route. <code>findClosestByPath()</code>, <code>findPathTo()</code>, <code>PathFinder.search()</code>, and <code>moveTo()</code> involve pathfinding.</p>

<h2 id="two-distances">Linear range and path distance</h2>
<div class="table-scroll"><table>
<thead><tr><th>Question</th><th>Use</th></tr></thead>
<tbody>
<tr><td>Can the action run now?</td><td>Linear range</td></tr>
<tr><td>Are two coordinates equal or adjacent?</td><td>Equality or range</td></tr>
<tr><td>Which target is geometrically closest?</td><td>Closest by range</td></tr>
<tr><td>Which target has the shortest usable route?</td><td>Closest by path</td></tr>
<tr><td>Which rooms should a Creep cross?</td><td>Map-level routing</td></tr>
</tbody></table></div>
<p>In an eight-direction grid, diagonal displacement counts by the larger coordinate difference. From (10,10) to (13,12), the linear range is 3.</p>

<h2 id="range-methods">getRangeTo() and inRangeTo()</h2>
<pre><code class="language-javascript">const range = creep.pos.getRangeTo(target);

if (creep.pos.inRangeTo(target, 3)) {
  // A documented range-3 action may run.
}</code></pre>
<p><code>getRangeTo()</code> returns a number. <code>inRangeTo()</code> returns a boolean and expresses the business rule more directly.</p>
<pre><code class="language-javascript">function getSameRoomRange(from, to) {
  if (
    !from
    || !to
    || from.roomName !== to.roomName
  ) {
    return null;
  }

  return Math.max(
    Math.abs(from.x - to.x),
    Math.abs(from.y - to.y)
  );
}</code></pre>

<h2 id="near-equal">isNearTo() and isEqualTo()</h2>
<pre><code class="language-javascript">const withinOne = creep.pos.isNearTo(target);
const sameTile = creep.pos.isEqualTo(target);
const strictlyAdjacent = withinOne && !sameTile;</code></pre>
<p>The official API defines <code>isNearTo(target)</code> as the same test as <code>inRangeTo(target, 1)</code>. That includes range 0. Game objects such as a Creep and a solid Structure usually cannot occupy the same tile, but pure RoomPosition comparisons can.</p>

<h2 id="closest">Closest by range or path</h2>
<pre><code class="language-javascript">const linearTarget = creep.pos.findClosestByRange(
  FIND_HOSTILE_CREEPS
);

const reachableSource = creep.pos.findClosestByPath(
  FIND_SOURCES_ACTIVE
);</code></pre>
<div class="table-scroll"><table>
<thead><tr><th>Method</th><th>Terrain and blockers</th><th>Typical use</th></tr></thead>
<tbody>
<tr><td><code>findClosestByRange()</code></td><td>No</td><td>Tower target, quick shortlist, geometry</td></tr>
<tr><td><code>findClosestByPath()</code></td><td>Yes</td><td>A Creep must travel to one candidate</td></tr>
</tbody></table></div>
<p>Both return <code>null</code> when no matching candidate is found. Path-based selection can also return <code>null</code> when candidates exist but no path is available under the supplied options.</p>

<h2 id="find-in-range">Filter candidates with findInRange()</h2>
<pre><code class="language-javascript">const hostiles = tower.pos.findInRange(
  FIND_HOSTILE_CREEPS,
  10
);</code></pre>
<p>This returns every candidate inside the linear range. It is useful before sorting by hits, role, threat, or another rule. It does not test reachability.</p>

<h2 id="cross-room">Do not compare local coordinates across rooms</h2>
<pre><code class="language-javascript">if (from.roomName !== to.roomName) {
  return {
    comparable: false,
    reason: 'different-rooms'
  };
}</code></pre>
<p>Every room reuses local coordinates 0–49. Two positions at (25,25) in different rooms are not the same world location. Use <a href="/en/blog/screeps-map-find-route">Game.map.findRoute()</a>, PathFinder, or <code>moveTo()</code> for cross-room travel.</p>

<h2 id="relation-helper">Complete same-room relation helper</h2>
<pre><code class="language-javascript">function describePositionRelation(
  from,
  to,
  requiredRange
) {
  if (
    !from
    || !to
    || from.roomName !== to.roomName
    || !Number.isInteger(requiredRange)
    || requiredRange < 0
  ) {
    return {
      comparable: false,
      sameTile: false,
      withinOne: false,
      strictlyAdjacent: false,
      inRequiredRange: false,
      range: null
    };
  }

  const range = Math.max(
    Math.abs(from.x - to.x),
    Math.abs(from.y - to.y)
  );

  return {
    comparable: true,
    sameTile: range === 0,
    withinOne: range <= 1,
    strictlyAdjacent: range === 1,
    inRequiredRange: range <= requiredRange,
    range
  };
}</code></pre>
<p>This pure function verifies coordinate semantics. It does not inspect terrain, structures, Creeps, or path callbacks.</p>

<h2 id="action-example">Use the required action range</h2>
<p><strong>State impact:</strong> this example may submit one movement order. It does not write Memory.</p>
<pre><code class="language-javascript">const ACTION_RANGE = {
  harvest: 1,
  withdraw: 1,
  transfer: 1,
  pickup: 1,
  build: 3,
  repair: 3,
  upgrade: 3
};

function prepareForAction(creep, target, action) {
  if (!creep || !target?.pos) {
    return {
      status: 'object-invalid'
    };
  }

  const requiredRange = ACTION_RANGE[action];

  if (!Number.isInteger(requiredRange)) {
    return {
      status: 'action-range-unknown'
    };
  }

  if (
    creep.pos.roomName === target.pos.roomName
    && creep.pos.inRangeTo(target, requiredRange)
  ) {
    return {
      status: 'action-range-ready',
      requiredRange,
      range: creep.pos.getRangeTo(target)
    };
  }

  const moveResult = creep.moveTo(target, {
    range: requiredRange,
    reusePath: 10
  });

  return {
    status: moveResult === OK
      ? 'move-submitted'
      : 'move-failed',
    requiredRange,
    moveResult
  };
}</code></pre>
<p>Do not force every action to range 1. Build, repair, and Controller upgrade work at range 3. The range option tells pathfinding where it may stop; it does not change the action's API.</p>

<h2 id="reachability">Range does not prove reachability</h2>
<p>Two coordinates can have range 2 while a wall, hostile Rampart, Structure, room edge, CostMatrix rule, or traffic pattern prevents direct travel. Range answers “how far apart are the coordinates?” Pathfinding answers “how can this Creep travel under these rules?”</p>
<p>Likewise, a Controller at range 3 is ready for upgrading even when the shortest route to that position would have required many earlier steps. Action range and path length are different measurements.</p>

<h2 id="debugging">Debugging checklist</h2>
<ul>
<li>Check <code>roomName</code> before same-room range logic.</li>
<li>Use <code>isEqualTo()</code> for exact coordinates.</li>
<li>Remember that <code>isNearTo()</code> includes range 0.</li>
<li>Use <code>inRangeTo()</code> for action readiness.</li>
<li>Use <code>findClosestByRange()</code> only when linear proximity is intended.</li>
<li>Use <code>findClosestByPath()</code> when a Creep must travel.</li>
<li>Handle <code>null</code> from both closest-target methods.</li>
<li>Do not use pathfinding merely to check an already-satisfied action range.</li>
<li>Do not use range as proof of reachability.</li>
</ul>

<h2 id="scope">Scope and next steps</h2>
<p>This guide does not compare PathFinder heuristics, CPU cost across large candidate sets, multi-room linear distance, portals, traffic reservations, or route caching. Continue with <a href="/en/blog/screeps-map-find-route">cross-room route planning</a>.</p>

<h2 id="faq">Frequently asked questions</h2>
<h3>Does getRangeTo() consider obstacles?</h3>
<p>No. It is a linear coordinate measurement.</p>
<h3>Does isNearTo() mean exactly one tile away?</h3>
<p>No. It means range is at most 1. Exclude <code>isEqualTo()</code> for strict adjacency.</p>
<h3>Which closest method should a moving Creep use?</h3>
<p>Use path-based selection when route length and reachability matter.</p>
<h3>Can local x and y compare different rooms?</h3>
<p>No. Check room names and use map or path routing.</p>

<h2 id="official-docs">Official documentation</h2>
<ul>
<li><a href="https://docs.screeps.com/api/#RoomPosition.getRangeTo" rel="nofollow">API Reference: RoomPosition.getRangeTo()</a></li>
<li><a href="https://docs.screeps.com/api/#RoomPosition.inRangeTo" rel="nofollow">API Reference: RoomPosition.inRangeTo()</a></li>
<li><a href="https://docs.screeps.com/api/#RoomPosition.isNearTo" rel="nofollow">API Reference: RoomPosition.isNearTo()</a></li>
<li><a href="https://docs.screeps.com/api/#RoomPosition.isEqualTo" rel="nofollow">API Reference: RoomPosition.isEqualTo()</a></li>
<li><a href="https://docs.screeps.com/api/#RoomPosition.findClosestByRange" rel="nofollow">API Reference: findClosestByRange()</a></li>
<li><a href="https://docs.screeps.com/api/#RoomPosition.findClosestByPath" rel="nofollow">API Reference: findClosestByPath()</a></li>
</ul>`,
  },
  {
    slug: "screeps-map-find-route",
    path: "/en/blog/screeps-map-find-route",
    chinesePath: "/blog/screeps-map-find-route",
    title: "Screeps Game.map.findRoute(): Cross-Room Routing",
    headline: "How to Plan and Execute a Cross-Room Route in Screeps",
    description:
      "Use Game.map.findRoute() as a room-level plan, assign routeCallback costs, reject rooms deliberately, validate the first exit step, rebuild after room transitions, and keep route preference separate from live safety intel.",
    category: "MOVEMENT · CROSS-ROOM ROUTING",
    publishedAt: "2026-07-25",
    publishedLabel: "July 25, 2026",
    readingTime: "18 min read",
    breadcrumbLabel: "Cross-Room Routing",
    tags: ["Screeps", "Game.map", "findRoute", "Cross-Room", "Pathfinding"],
    keywords: [
      "Screeps Game.map.findRoute",
      "Screeps cross room movement",
      "routeCallback Infinity Screeps",
      "Screeps highway room route",
      "Screeps route cache",
    ],
    primaryKeyword: "Screeps Game.map.findRoute",
    searchIntent: "Build, validate, and execute an explainable room-level route",
    finalScore: 98,
    verification: [
      ["Chinese source article", "Reviewed in full"],
      ["Official docs", "Checked — findRoute(), findExit(), describeExits() and routeCallback"],
      ["Routing boundary", "Room-level route steps are separated from tile-level pathfinding"],
      ["Source correction", "A route rebuilt from the current room uses and validates its first step instead of searching the entire stored route for a matching exit"],
      ["JavaScript syntax", "Passed"],
      ["Offline route review", "Passed — same room, invalid names, avoided rooms, highway costs, ERR_NO_PATH, exit validation and room transitions"],
      ["Screeps Console test", "Pending"],
      ["Live cross-room movement test", "Pending"],
      ["Last verified", "July 25, 2026"],
    ],
    toc: [
      ["quick-answer", "Quick answer"],
      ["two-levels", "Room routes and tile paths"],
      ["return-value", "Handle arrays and error codes"],
      ["route-cost", "routeCallback is an entry cost"],
      ["highways", "Classify highway rooms"],
      ["intel", "No vision does not mean safe"],
      ["route-builder", "Build and validate a route"],
      ["complete-example", "Complete per-room route executor"],
      ["cache", "Why the plan rebuilds after each room"],
      ["infinity", "Use Infinity deliberately"],
      ["destination", "Entering the target room is not task completion"],
      ["debugging", "Debugging checklist"],
      ["scope", "Scope and next steps"],
      ["faq", "FAQ"],
      ["official-docs", "Official documentation"],
    ],
    faq: [
      [
        "Does Game.map.findRoute() move the Creep?",
        "No. It returns room-level exit steps. Your code still needs to choose an exit tile and submit movement.",
      ],
      [
        "What does Infinity mean in routeCallback?",
        "It completely rejects entry into that room. If all possible corridors are rejected, findRoute() can return ERR_NO_PATH.",
      ],
      [
        "Is a preferred highway route automatically safe?",
        "No. A room-name classification is not live hostile, Tower, ownership, or event intel.",
      ],
      [
        "Why rebuild the route after crossing a room boundary?",
        "The current room changed. Rebuilding creates a recoverable first step and avoids relying on a stale index after pushes, portals, route-policy changes, or unexpected movement.",
      ],
    ],
    previous: {
      href: "/en/blog/screeps-roomposition-distance",
      label: "Previous position guide",
      title: "Choose the Correct Distance Method",
    },
    next: {
      href: "/en/blog",
      label: "Continue reading",
      title: "Return to English Articles",
    },
    articleHtml: String.raw`
<h2 id="quick-answer">Quick answer</h2>
<p><code>Game.map.findRoute(fromRoom, toRoom)</code> creates a high-level sequence of rooms and exit directions. It does not move a Creep and does not return every tile. Handle <code>ERR_NO_PATH</code> before reading the array, assign room-entry costs with <code>routeCallback</code>, validate the first step against <code>describeExits()</code>, move toward that exit, and rebuild from the new current room after crossing the boundary.</p>

<h2 id="two-levels">Room routes and tile paths</h2>
<div class="table-scroll"><table>
<thead><tr><th>Tool</th><th>Level</th><th>Result</th></tr></thead>
<tbody>
<tr><td><code>Game.map.findRoute()</code></td><td>Rooms</td><td>Exit direction and next room</td></tr>
<tr><td><code>Game.map.findExit()</code></td><td>Current room</td><td>Exit direction toward another room</td></tr>
<tr><td><code>PathFinder.search()</code></td><td>Tiles</td><td>RoomPosition path and search metadata</td></tr>
<tr><td><code>creep.moveTo()</code></td><td>Movement command</td><td>Scheduled order or error code</td></tr>
</tbody></table></div>
<p>A valid room sequence does not prove that the tile-level path, traffic state, hostile Ramparts, or live room conditions permit safe travel.</p>

<h2 id="return-value">Handle arrays and error codes</h2>
<pre><code class="language-javascript">function calculateRoomRoute(fromRoom, targetRoom) {
  if (fromRoom === targetRoom) {
    return {
      ok: true,
      code: OK,
      steps: []
    };
  }

  const route = Game.map.findRoute(
    fromRoom,
    targetRoom
  );

  if (!Array.isArray(route)) {
    return {
      ok: false,
      code: route,
      steps: []
    };
  }

  return {
    ok: true,
    code: OK,
    steps: route
  };
}</code></pre>
<p>Never call <code>[0].exit</code> before checking that the result is an array with a first step. The same-room case is successful completion, not a routing error.</p>

<h2 id="route-cost">routeCallback is an entry cost</h2>
<pre><code class="language-javascript">routeCallback(roomName, fromRoomName) {
  if (Memory.routeAvoid?.includes(roomName)) {
    return Infinity;
  }

  if (isPreferredRoom(roomName)) {
    return 1;
  }

  return 2.5;
}</code></pre>
<p>Lower values are preferred. <code>Infinity</code> rejects the room completely. Values such as 1 and 2.5 are policy weights, not official recommendations and not travel time in ticks.</p>

<h2 id="highways">Classify highway rooms</h2>
<pre><code class="language-javascript">function isHighwayRoom(roomName) {
  const match = /^[WE](\d+)[NS](\d+)$/.exec(
    roomName
  );

  if (!match) {
    return false;
  }

  const horizontal = Number(match[1]);
  const vertical = Number(match[2]);

  return horizontal % 10 === 0
    || vertical % 10 === 0;
}</code></pre>
<p>This classifies a room name. It does not prove that the room is open, safe, visible, unreserved, or free of hostiles.</p>

<h2 id="intel">No vision does not mean safe</h2>
<p><code>Game.rooms[roomName]</code> exists only when the room is visible. Without vision, a route callback cannot directly read current hostile Creeps, Towers, Controller ownership, Invader Cores, Nukes, or temporary combat conditions. Use your own timestamped intel summary when those facts affect routing.</p>
<pre><code class="language-javascript">function getIntelRisk(roomName) {
  const intel = Memory.roomIntel?.[roomName];

  if (!intel || Game.time - intel.seenAt > 5000) {
    return 'unknown';
  }

  return intel.risk;
}</code></pre>
<p>The 5,000-tick age is an example policy, not an official safe value.</p>

<h2 id="route-builder">Build and validate a route</h2>
<pre><code class="language-javascript">function getRouteRoomCost(
  roomName,
  avoidedRooms
) {
  if (avoidedRooms.has(roomName)) {
    return Infinity;
  }

  const visibleRoom = Game.rooms[roomName];
  const owned = Boolean(
    visibleRoom?.controller?.my
  );

  if (owned || isHighwayRoom(roomName)) {
    return 1;
  }

  return 2.5;
}

function calculateRoute(fromRoom, targetRoom) {
  if (fromRoom === targetRoom) {
    return {
      ok: true,
      code: OK,
      steps: []
    };
  }

  const avoidedRooms = new Set(
    Array.isArray(Memory.routeAvoid)
      ? Memory.routeAvoid
      : []
  );

  const route = Game.map.findRoute(
    fromRoom,
    targetRoom,
    {
      routeCallback(roomName) {
        return getRouteRoomCost(
          roomName,
          avoidedRooms
        );
      }
    }
  );

  if (!Array.isArray(route)) {
    return {
      ok: false,
      code: route,
      steps: []
    };
  }

  return {
    ok: true,
    code: OK,
    steps: route.map(step => ({
      exit: step.exit,
      room: step.room
    }))
  };
}</code></pre>

<h2 id="complete-example">Complete per-room route executor</h2>
<p><strong>State impact:</strong> this script writes <code>creep.memory.routePlan</code> and may submit one movement order. It rebuilds the plan whenever the current room or destination changes.</p>
<pre><code class="language-javascript">function isHighwayRoom(roomName) {
  const match = /^[WE](\d+)[NS](\d+)$/.exec(
    roomName
  );

  if (!match) {
    return false;
  }

  return Number(match[1]) % 10 === 0
    || Number(match[2]) % 10 === 0;
}

function calculateRoute(fromRoom, targetRoom) {
  const avoidedRooms = new Set(
    Array.isArray(Memory.routeAvoid)
      ? Memory.routeAvoid
      : []
  );

  const route = Game.map.findRoute(
    fromRoom,
    targetRoom,
    {
      routeCallback(roomName) {
        if (avoidedRooms.has(roomName)) {
          return Infinity;
        }

        const room = Game.rooms[roomName];
        const owned = Boolean(
          room?.controller?.my
        );

        return owned || isHighwayRoom(roomName)
          ? 1
          : 2.5;
      }
    }
  );

  if (!Array.isArray(route)) {
    return {
      ok: false,
      code: route,
      steps: []
    };
  }

  return {
    ok: true,
    code: OK,
    steps: route
  };
}

function getValidatedFirstStep(creep, targetRoom) {
  creep.memory.routePlan ??= {};
  const plan = creep.memory.routePlan;
  const needsRebuild =
    plan.targetRoom !== targetRoom
    || plan.fromRoom !== creep.room.name
    || !Array.isArray(plan.steps);

  if (needsRebuild) {
    const result = calculateRoute(
      creep.room.name,
      targetRoom
    );

    if (!result.ok) {
      return result;
    }

    creep.memory.routePlan = {
      targetRoom,
      fromRoom: creep.room.name,
      steps: result.steps,
      builtAt: Game.time
    };
  }

  const currentPlan = creep.memory.routePlan;
  const step = currentPlan.steps[0];

  if (!step) {
    return {
      ok: false,
      code: ERR_NO_PATH,
      steps: []
    };
  }

  const exits = Game.map.describeExits(
    creep.room.name
  );

  if (!exits || exits[step.exit] !== step.room) {
    delete creep.memory.routePlan;
    return {
      ok: false,
      code: ERR_NO_PATH,
      steps: []
    };
  }

  return {
    ok: true,
    code: OK,
    step
  };
}

module.exports.loop = function () {
  const creep = Game.creeps.Scout1;
  const targetRoom = 'W8N3';

  if (!creep) {
    return;
  }

  if (creep.room.name === targetRoom) {
    delete creep.memory.routePlan;
    return;
  }

  const routeResult = getValidatedFirstStep(
    creep,
    targetRoom
  );

  if (!routeResult.ok || !routeResult.step) {
    if (Game.time % 100 === 0) {
      console.log(JSON.stringify({
        type: 'route-not-found',
        creepName: creep.name,
        roomName: creep.room.name,
        targetRoom,
        code: routeResult.code
      }));
    }
    return;
  }

  const exitPosition =
    creep.pos.findClosestByRange(
      routeResult.step.exit
    );

  if (!exitPosition) {
    delete creep.memory.routePlan;
    return;
  }

  const moveResult = creep.moveTo(
    exitPosition,
    {
      reusePath: 10,
      maxRooms: 1
    }
  );

  if (
    moveResult !== OK
    && moveResult !== ERR_TIRED
    && Game.time % 20 === 0
  ) {
    console.log(JSON.stringify({
      type: 'route-move-failed',
      creepName: creep.name,
      roomName: creep.room.name,
      nextRoom: routeResult.step.room,
      moveResult
    }));
  }
};</code></pre>
<p>The first step is correct because the route was built from the current room. Validating it against <code>describeExits()</code> prevents a stale or malformed step from being executed.</p>

<h2 id="cache">Why the plan rebuilds after each room</h2>
<p>When the Creep crosses an exit, <code>plan.fromRoom !== creep.room.name</code> becomes true and the route is rebuilt. This design is intentionally simple and recoverable. A whole-route cursor can save route calculations, but then it must handle pushes, portals, unexpected rooms, changing avoidance policy, stale intel, and shared cache versions.</p>

<h2 id="infinity">Use Infinity deliberately</h2>
<p><code>Infinity</code> means “never enter this room.” It is appropriate for a hard block, not merely a preference. A civilian hauler, emergency defender, and scout may need different route policies. Returning a large finite cost keeps a risky corridor available as a last resort; returning <code>Infinity</code> removes it.</p>

<h2 id="destination">Entering the target room is not task completion</h2>
<p>The example stops when <code>creep.room.name === targetRoom</code>. Real role code must then choose a destination position, Flag, Controller, Structure, or object ID inside the room. Crossing the room boundary does not mean the final task has completed.</p>

<h2 id="debugging">Debugging checklist</h2>
<ul>
<li>Handle same-room completion before routing.</li>
<li>Check for an array before reading route steps.</li>
<li>Treat route weights as preferences, not travel ticks.</li>
<li>Use <code>Infinity</code> only for hard rejection.</li>
<li>Do not interpret missing vision as safety.</li>
<li>Validate the first step with <code>describeExits()</code>.</li>
<li>Rebuild after the current room changes.</li>
<li>Handle a missing exit position.</li>
<li>Log the movement result separately from the route result.</li>
<li>Remember that room-level success does not prove a tile-level path.</li>
</ul>

<h2 id="scope">Scope and next steps</h2>
<p>This guide does not implement persistent shared route caches, portals, shard travel, hostile-room scoring, SK-room timing, traffic reservations, room-status policy, or destination behavior. Console and live cross-room verification remain Pending.</p>

<h2 id="faq">Frequently asked questions</h2>
<h3>Does findRoute() return tile coordinates?</h3>
<p>No. It returns room-level exit steps.</p>
<h3>What happens when routeCallback returns Infinity?</h3>
<p>The room is rejected. Rejecting every corridor can produce <code>ERR_NO_PATH</code>.</p>
<h3>Are highways always safe?</h3>
<p>No. Highway classification is only a room-name property.</p>
<h3>Why use only the first route step?</h3>
<p>The route was built from the current room, so its first step is the next room transition. Rebuild after crossing.</p>

<h2 id="official-docs">Official documentation</h2>
<ul>
<li><a href="https://docs.screeps.com/api/#Game.map.findRoute" rel="nofollow">API Reference: Game.map.findRoute()</a></li>
<li><a href="https://docs.screeps.com/api/#Game.map.findExit" rel="nofollow">API Reference: Game.map.findExit()</a></li>
<li><a href="https://docs.screeps.com/api/#Game.map.describeExits" rel="nofollow">API Reference: Game.map.describeExits()</a></li>
<li><a href="https://docs.screeps.com/api/#RoomPosition.findClosestByRange" rel="nofollow">API Reference: RoomPosition.findClosestByRange()</a></li>
<li><a href="https://docs.screeps.com/api/#Creep.moveTo" rel="nofollow">API Reference: Creep.moveTo()</a></li>
</ul>`,
  },
] satisfies EnglishBeginnerArticle[];

export const englishMovementBatchSixBySlug = Object.fromEntries(
  englishMovementBatchSixArticles.map((article) => [article.slug, article]),
) as Record<string, EnglishBeginnerArticle>;

export function getEnglishMovementBatchSixArticle(
  slug: string,
): EnglishBeginnerArticle | undefined {
  return englishMovementBatchSixBySlug[slug];
}
