import type { EnglishArticleRecord } from "./english-articles";

export const englishLinkSourceBatchEighteenRegistry: EnglishArticleRecord[] = [
  {
    href: "/en/blog/screeps-link-transfer-energy",
    chinesePath: "/blog/screeps-link-transfer-energy",
    category: "LOGISTICS · LINK ENERGY NETWORK",
    title: "How to Transfer Link Energy Without Depending on Structure Array Order",
    description:
      "Recover source and target Links by fixed IDs, require ownership, different objects, the same room, active structures and zero source cooldown, calculate a conservative amount from source stock and target free capacity, estimate LINK_LOSS_RATIO only for logs, and verify Store changes later.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps Link transferEnergy",
    searchIntent: "Transfer Energy between two explicitly identified owned Links with conservative capacity and cooldown checks",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Link transferEnergy",
      "Screeps Link cooldown",
      "Screeps LINK_LOSS_RATIO",
      "Screeps controller Link",
      "Screeps Link Energy amount",
    ],
  },
  {
    href: "/en/blog/screeps-select-source-by-path",
    chinesePath: "/blog/screeps-select-source-by-path",
    category: "HARVESTING · SOURCE TARGET SELECTION",
    title: "How to Select an Active Source by Reachable Path Without Target Churn",
    description:
      "Recover a stored Source ID first, distinguish FIND_SOURCES from FIND_SOURCES_ACTIVE, build reachable path candidates, rank path length before assignment count and stable ID, store the selected identity, handle empty Sources according to a documented dynamic policy, and preserve harvest and movement results.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps select Source by path",
    searchIntent: "Keep or select a reachable active Source with deterministic path and load ordering",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps select Source by path",
      "Screeps FIND_SOURCES_ACTIVE",
      "Screeps Source assignment count",
      "Screeps store Source ID",
      "Screeps findClosestByPath Source",
    ],
  },
  {
    href: "/en/blog/screeps-tombstone-ruin-recovery",
    chinesePath: "/blog/screeps-tombstone-ruin-recovery",
    category: "ROOM ECONOMY · RESOURCE RECOVERY",
    title: "How to Recover Resources from Tombstones and Ruins in Screeps",
    description:
      "Scan visible Tombstones and Ruins, rank candidates by ticksToDecay, resource priority, amount and range, submit withdraw() safely, and verify bounded Store deltas on a later tick.",
    publishedAt: "2026-08-04",
    publishedLabel: "August 4, 2026",
    readingTime: "17 min read",
    primaryKeyword: "Screeps Tombstone resource recovery",
    searchIntent: "Recover expiring resources from visible Tombstones and Ruins with deterministic target selection and bounded verification",
    status: "published",
    finalScore: 97,
    keywords: [
      "Screeps Tombstone resource recovery",
      "Screeps Ruin withdraw",
      "FIND_TOMBSTONES",
      "FIND_RUINS",
      "Creep.withdraw Tombstone",
    ],
  },
  {
    href: "/en/blog/screeps-room-energyavailable-stuck",
    chinesePath: "/blog/screeps-room-energyavailable-stuck",
    category: "SPAWN SYSTEM · ENERGY DIAGNOSTICS",
    title: "Why room.energyAvailable Stays Below Capacity in Screeps",
    description:
      "Inspect active Spawn and Extension Stores, distinguish a real delivery failure from normal spawning demand, select one deterministic fill target, record transfer() results, and verify bounded later deltas.",
    publishedAt: "2026-08-04",
    publishedLabel: "August 4, 2026",
    readingTime: "15 min read",
    primaryKeyword: "Screeps room.energyAvailable",
    searchIntent: "Diagnose why room.energyAvailable remains below energyCapacityAvailable and verify one Spawn or Extension delivery attempt",
    status: "published",
    finalScore: 97,
    keywords: [
      "Screeps room.energyAvailable",
      "energyCapacityAvailable",
      "Screeps Extension not filling",
      "Screeps Spawn energy",
      "Creep.transfer Extension",
    ],
  },
  {
    href: "/en/blog/screeps-market-order-maintenance",
    chinesePath: "/blog/screeps-market-order-maintenance",
    category: "MARKET · ORDER LIFECYCLE",
    title: "How to Maintain Screeps Market Orders Safely",
    description:
      "Resolve one current owned order, require an exact order fingerprint, estimate change-price or extension fees, protect a Credits reserve, submit one changeOrderPrice(), extendOrder(), or cancelOrder() request, and verify the later order state.",
    publishedAt: "2026-08-04",
    publishedLabel: "August 4, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps market order maintenance",
    searchIntent: "Safely change, extend, or cancel one owned Screeps market order and verify the result",
    status: "published",
    finalScore: 97,
    keywords: [
      "Screeps changeOrderPrice",
      "Screeps extendOrder",
      "Screeps cancelOrder",
      "Screeps market order fee",
      "Screeps market order maintenance",
    ],
  },
  {
    href: "/en/blog/screeps-upgrader-controller-link-not-upgrading",
    chinesePath: "/blog/screeps-upgrader-controller-link-not-upgrading",
    category: "CONTROLLER · FIXED UPGRADER DIAGNOSTICS",
    title: "Why a Fixed Screeps Upgrader Is Not Upgrading",
    description:
      "Validate one fixed anchor against Controller range 3 and Link range 1, recover the exact owned Controller Link, diagnose Energy and active body parts, preserve move, withdraw, and upgrade return codes, and verify later position, Store, or event evidence.",
    publishedAt: "2026-08-05",
    publishedLabel: "August 5, 2026",
    readingTime: "20 min read",
    primaryKeyword: "Screeps Upgrader not upgrading",
    searchIntent: "Diagnose a fixed Upgrader that reached the Controller area but is not consuming Controller Link Energy or upgrading",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Upgrader not upgrading",
      "Screeps Controller Link",
      "Screeps fixed Upgrader",
      "upgradeController return codes",
      "Screeps Controller Link Energy",
    ],
  },
  {
    href: "/en/blog/screeps-creep-prespawn-replacement",
    chinesePath: "/blog/screeps-creep-prespawn-replacement",
    category: "SPAWN LIFECYCLE · PRESPAWN REPLACEMENT",
    title: "Screeps Prespawn Replacement: Start the Next Creep Before the Current One Dies",
    description:
      "Calculate a replacement deadline from ticksToLive, current Spawn work, body spawn time, travel and safety margin, prevent duplicate role replacements, preserve spawnCreep results, and observe the accepted name later.",
    publishedAt: "2026-08-03",
    publishedLabel: "August 3, 2026",
    readingTime: "17 min read",
    primaryKeyword: "Screeps prespawn replacement",
    searchIntent: "Prevent role downtime by starting one covered Creep replacement before the current unit dies",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps prespawn replacement",
      "Screeps ticksToLive replacement",
      "Screeps Spawn queue",
      "Creep replacement timing",
      "prevent Screeps role downtime",
    ],
  },
  {
    href: "/en/blog/screeps-cpu-bucket-degradation",
    chinesePath: "/blog/screeps-cpu-bucket-degradation",
    category: "OPERATIONS · CPU DEGRADATION",
    title: "Screeps CPU Bucket Degradation: Protect Critical Tasks and Recover Gradually",
    description:
      "Use a hysteresis-based four-mode scheduler when Game.cpu.bucket keeps falling, protect Spawn, harvesting, Controller safety and defense, throttle lower-tier work, stagger recovery, and preserve explicit evidence boundaries.",
    publishedAt: "2026-08-05",
    publishedLabel: "August 5, 2026",
    readingTime: "16 min read",
    primaryKeyword: "Screeps CPU bucket falling",
    searchIntent: "Protect critical Screeps tasks and degrade optional work safely when CPU bucket trends downward",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps CPU bucket falling",
      "Screeps CPU degradation",
      "Screeps CPU scheduler",
      "Game.cpu.bucket recovery",
      "Screeps optional task throttling",
    ],
  },
];