import type { EnglishArticleRecord } from "./english-articles";

export const englishLabFactoryBatchElevenRegistry: EnglishArticleRecord[] = [
  {
    href: "/en/blog/screeps-lab-run-reaction",
    chinesePath: "/blog/screeps-lab-run-reaction",
    category: "RESOURCES · LAB REACTION WORKFLOW",
    title: "How to Run Lab Reactions Safely in Screeps",
    description:
      "Validate three owned active Labs, resolve the REACTIONS recipe, check reagent stores, output mineral compatibility, free capacity, range 2, cooldown, and a one-time production request before calling runReaction() and verifying the next tick.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps StructureLab runReaction",
    searchIntent: "Run one validated Lab reaction and verify the output afterward",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps StructureLab runReaction",
      "Screeps lab reaction range",
      "Screeps REACTIONS constant",
      "Screeps lab cooldown",
      "Screeps reaction output capacity",
    ],
  },
  {
    href: "/en/blog/screeps-lab-boost-creep",
    chinesePath: "/blog/screeps-lab-boost-creep",
    category: "RESOURCES · LAB BOOST WORKFLOW",
    title: "How to Boost Creep Body Parts Safely in Screeps",
    description:
      "Match a Lab mineral to BOOSTS, count eligible unboosted body parts, calculate LAB_BOOST_MINERAL and LAB_BOOST_ENERGY budgets, enforce range 1, ownership and activity, submit one reviewed boost request, and verify exact body-part changes afterward.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps StructureLab boostCreep",
    searchIntent: "Boost a controlled number of eligible Creep parts with exact resource safeguards",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps StructureLab boostCreep",
      "Screeps LAB_BOOST_MINERAL",
      "Screeps LAB_BOOST_ENERGY",
      "Screeps BOOSTS constant",
      "Screeps boost eligible parts",
    ],
  },
  {
    href: "/en/blog/screeps-factory-produce",
    chinesePath: "/blog/screeps-factory-produce",
    category: "RESOURCES · FACTORY PRODUCTION WORKFLOW",
    title: "How to Produce Factory Commodities Safely in Screeps",
    description:
      "Validate an owned active Factory, resolve the COMMODITIES recipe, check all components and output capacity, respect cooldown, match commodity level to the Factory level and PWR_OPERATE_FACTORY effect, submit one reviewed production request, and verify Store deltas afterward.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps StructureFactory produce",
    searchIntent: "Produce one commodity with complete component, capacity, cooldown, level, and Power checks",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps StructureFactory produce",
      "Screeps COMMODITIES components",
      "Screeps PWR_OPERATE_FACTORY",
      "Screeps factory level",
      "Screeps factory cooldown",
    ],
  },
];
