import type { DatedEnglishArticleRecord } from "./english-article-record-types";

export const englishControllerBatchFourteenRegistry: DatedEnglishArticleRecord[] = [
  {
    href: "/en/blog/screeps-controller-activate-safe-mode",
    chinesePath: "/blog/screeps-controller-activate-safe-mode",
    category: "CONTROLLER · SAFE MODE ACTIVATION",
    title: "How to Activate Safe Mode Without Accidental Repeated Use",
    description:
      "Use an explicit one-time Memory request, confirmation phrase, owned Controller checks, safeMode, safeModeAvailable, safeModeCooldown and upgradeBlocked preflight, disable before activateSafeMode(), save the return code, and verify later state.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps activateSafeMode",
    searchIntent: "Activate Safe Mode once with explicit confirmation and current Controller evidence",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps activateSafeMode",
      "Screeps safeModeAvailable",
      "Screeps safeModeCooldown",
      "Screeps Controller ERR_BUSY",
      "Screeps Safe Mode request",
    ],
  },
  {
    href: "/en/blog/screeps-controller-downgrade",
    chinesePath: "/blog/screeps-controller-downgrade",
    category: "CONTROLLER · DOWNGRADE RECOVERY",
    title: "How to Detect Controller Downgrade Risk and Recover Safely",
    description:
      "Compare ticksToDowngrade with configurable enter and recovery thresholds, use CONTROLLER_DOWNGRADE for context, select an owned ready Upgrader with Energy and active WORK, move to range 3, save upgradeController() results, and exit emergency mode only after recovery.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps Controller downgrade",
    searchIntent: "Enter and leave an emergency Controller upgrading state without threshold flapping",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Controller downgrade",
      "Screeps ticksToDowngrade",
      "Screeps CONTROLLER_DOWNGRADE",
      "Screeps emergency upgrader",
      "Screeps upgradeController range 3",
    ],
  },
  {
    href: "/en/blog/screeps-reserve-vs-claim-controller",
    chinesePath: "/blog/screeps-reserve-vs-claim-controller",
    category: "CONTROLLER · RESERVE AND CLAIM IDENTITY",
    title: "Screeps reserveController() vs claimController(): Verify the Exact Mission",
    description:
      "Bind the Claimer and Controller IDs, record only accepted reserve or claim calls, verify reserve events without inventing a targetId, and verify claims through exact next-tick ownership.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    updatedAt: "2026-08-03",
    readingTime: "22 min read",
    primaryKeyword: "Screeps reserveController vs claimController verification",
    searchIntent: "Choose, submit, and verify one exact reserve or claim Controller mission without confusing an accepted call with completed state",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps reserveController vs claimController verification",
      "Screeps EVENT_RESERVE_CONTROLLER",
      "Screeps claimController next tick",
      "Screeps Controller mission identity",
      "Screeps remote reservation evidence",
    ],
  },
];
