import type { EnglishArticleRecord } from "./english-articles";

export const englishLinkSourceBatchEighteenRegistry: EnglishArticleRecord[] = [
  {
    href: "/en/blog/screeps-link-transfer-energy",
    chinesePath: "/blog/screeps-link-transfer-energy",
    category: "LOGISTICS · LINK ENERGY NETWORK",
    title: "How to Transfer Link Energy Without Depending on Structure Array Order",
    description:
      "Recover source and target Links by fixed IDs, require ownership, different objects, the same room, active structures and zero source cooldown, calculate a conservative amount from source stock and target free capacity, estimate LINK_LOSS_RATIO only for logs, and verify Store changes later.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps Link transferEnergy",
    searchIntent:
      "Transfer Energy between two explicitly identified owned Links with conservative capacity and cooldown checks",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Link transferEnergy",
      "Screeps Link cooldown",
      "Screeps LINK_LOSS_RATIO",
      "Screeps controller Link",
      "Screeps Link Energy amount",
    ],
  },
  {
    href: "/en/blog/screeps-select-source-by-path",
    chinesePath: "/blog/screeps-select-source-by-path",
    category: "HARVESTING · SOURCE TARGET SELECTION",
    title: "How to Select an Active Source by Reachable Path Without Target Churn",
    description:
      "Recover a stored Source ID first, distinguish FIND_SOURCES from FIND_SOURCES_ACTIVE, build reachable path candidates, rank path length before assignment count and stable ID, store the selected identity, handle empty Sources according to a documented dynamic policy, and preserve harvest and movement results.",
    publishedAt: "2026-07-26",
    publishedLabel: "July 26, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps select Source by path",
    searchIntent:
      "Keep or select a reachable active Source with deterministic path and load ordering",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps select Source by path",
      "Screeps FIND_SOURCES_ACTIVE",
      "Screeps Source assignment count",
      "Screeps store Source ID",
      "Screeps findClosestByPath Source",
    ],
  },
  {
    href: "/en/blog/screeps-tombstone-ruin-recovery",
    chinesePath: "/blog/screeps-tombstone-ruin-recovery",
    category: "ROOM ECONOMY · RESOURCE RECOVERY",
    title: "Screeps Tombstone and Ruin Recovery: Reach the Loot Before It Decays",
    description:
      "Recover Tombstone and Ruin resources without chasing doomed targets: reject incomplete structure-aware paths, block closed hostile Ramparts, preserve target identity, and verify the processed withdraw amount on the next tick.",
    publishedAt: "2026-08-04",
    publishedLabel: "August 4, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps Tombstone resource recovery",
    searchIntent:
      "Recover visible Tombstone and Ruin resources before decay without assigning incomplete or structure-blocked paths, then verify the processed withdrawal on the next tick",
    status: "published",
    finalScore: 99,
    keywords: [
      "Screeps Tombstone resource recovery",
      "Screeps Ruin withdraw",
      "Screeps ticksToDecay path",
      "Screeps Tombstone decay",
      "FIND_TOMBSTONES",
      "FIND_RUINS",
      "Creep.withdraw Tombstone",
    ],
    ...{ updatedAt: "2026-08-18" },
  },
  {
    href: "/en/blog/screeps-room-energyavailable-stuck",
    chinesePath: "/blog/screeps-room-energyavailable-stuck",
    category: "SPAWN SYSTEM · ENERGY DIAGNOSTICS",
    title: "Why room.energyAvailable Stays Below Capacity in Screeps",
    description:
      "Diagnose room.energyAvailable below energyCapacityAvailable by reconciling active Spawn and Extension Stores, holding one stable fill target, preserving transfer() results, and matching the processed Energy transfer on the next tick.",
    publishedAt: "2026-08-04",
    publishedLabel: "August 4, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps room.energyAvailable",
    searchIntent:
      "Diagnose why room.energyAvailable remains below energyCapacityAvailable by reconciling active Spawn and Extension Stores, stabilizing one reachable fill target, and verifying the processed transfer event",
    status: "published",
    finalScore: 99,
    keywords: [
      "Screeps room.energyAvailable",
      "Screeps energyCapacityAvailable",
      "Screeps Extension not filling",
      "Screeps Spawn energy",
      "Creep.transfer Extension",
      "Screeps EVENT_TRANSFER",
      "Screeps room energy stuck",
    ],
    ...{ updatedAt: "2026-08-18" },
  },
  {
    href: "/en/blog/screeps-market-order-maintenance",
    chinesePath: "/blog/screeps-market-order-maintenance",
    category: "MARKET · ORDER LIFECYCLE",
    title: "How to Maintain Screeps Market Orders Safely",
    description:
      "Resolve one current owned order, require an exact order fingerprint, estimate change-price or extension fees, protect a Credits reserve, submit one changeOrderPrice(), extendOrder(), or cancelOrder() request, and verify the later order state.",
    publishedAt: "2026-08-04",
    publishedLabel: "August 4, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps market order maintenance",
    searchIntent:
      "Safely change, extend, or cancel one owned Screeps market order and verify the result",
    status: "published",
    finalScore: 97,
    keywords: [
      "Screeps changeOrderPrice",
      "Screeps extendOrder",
      "Screeps cancelOrder",
      "Screeps market order fee",
      "Screeps market order maintenance",
    ],
  },
  {
    href: "/en/blog/screeps-upgrader-controller-link-not-upgrading",
    chinesePath: "/blog/screeps-upgrader-controller-link-not-upgrading",
    category: "CONTROLLER · FIXED UPGRADER DIAGNOSTICS",
    title: "Why a Fixed Screeps Upgrader Is Not Upgrading",
    description:
      "Validate one fixed anchor against Controller range 3 and Link range 1, recover the exact owned Controller Link, diagnose Energy and active body parts, preserve move, withdraw, and upgrade return codes, and verify later position, Store, or event evidence.",
    publishedAt: "2026-08-05",
    publishedLabel: "August 5, 2026",
    readingTime: "20 min read",
    primaryKeyword: "Screeps Upgrader not upgrading",
    searchIntent:
      "Diagnose a fixed Upgrader that reached the Controller area but is not consuming Controller Link Energy or upgrading",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Upgrader not upgrading",
      "Screeps Controller Link",
      "Screeps fixed Upgrader",
      "upgradeController return codes",
      "Screeps Controller Link Energy",
    ],
  },
  {
    href: "/en/blog/screeps-creep-prespawn-replacement",
    chinesePath: "/blog/screeps-creep-prespawn-replacement",
    category: "SPAWN LIFECYCLE · PRESPAWN REPLACEMENT",
    title: "Screeps Prespawn Replacement: Start the Next Creep Before the Current One Dies",
    description:
      "Calculate a replacement deadline from ticksToLive, current Spawn work, body spawn time, travel and safety margin, prevent duplicate role replacements, preserve spawnCreep results, and observe the accepted name later.",
    publishedAt: "2026-08-03",
    publishedLabel: "August 3, 2026",
    readingTime: "17 min read",
    primaryKeyword: "Screeps prespawn replacement",
    searchIntent:
      "Prevent role downtime by starting one covered Creep replacement before the current unit dies",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps prespawn replacement",
      "Screeps ticksToLive replacement",
      "Screeps Spawn queue",
      "Creep replacement timing",
      "prevent Screeps role downtime",
    ],
  },
  {
    href: "/en/blog/screeps-cpu-bucket-degradation",
    chinesePath: "/blog/screeps-cpu-bucket-degradation",
    category: "OPERATIONS · CPU DEGRADATION",
    title: "Screeps CPU Bucket Degradation: Protect Critical Tasks and Recover Gradually",
    description:
      "Use a hysteresis-based four-mode scheduler when Game.cpu.bucket keeps falling, protect Spawn, harvesting, Controller safety and defense, throttle lower-tier work, stagger recovery, and preserve explicit evidence boundaries.",
    publishedAt: "2026-08-05",
    publishedLabel: "August 5, 2026",
    readingTime: "16 min read",
    primaryKeyword: "Screeps CPU bucket falling",
    searchIntent:
      "Protect critical Screeps tasks and degrade optional work safely when CPU bucket trends downward",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps CPU bucket falling",
      "Screeps CPU degradation",
      "Screeps CPU scheduler",
      "Game.cpu.bucket recovery",
      "Screeps optional task throttling",
    ],
  },
  {
    href: "/en/blog/screeps-container-decay-repair-deadline",
    chinesePath: "/blog/screeps-container-decay-repair-deadline",
    category: "ROOM ECONOMY · CONTAINER DECAY",
    title: "Screeps Container Decay: Repair Before the Next Fatal Tick",
    description:
      "Treat ticksToDecay as the next decay pulse, estimate remaining Container decay events, include travel time, submit one maintenance action, and verify the exact event on the next tick.",
    publishedAt: "2026-08-06",
    publishedLabel: "August 6, 2026",
    readingTime: "14 min read",
    primaryKeyword: "Screeps Container decay",
    searchIntent:
      "Prevent a visible Container from being lost to decay by estimating the next fatal pulse and scheduling one verifiable maintenance action",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Container decay",
      "StructureContainer ticksToDecay",
      "Screeps Container maintenance",
      "CONTAINER_DECAY_TIME",
      "Screeps Container loss deadline",
    ],
  },
  {
    href: "/en/blog/screeps-spawn-exit-blocked-directions",
    chinesePath: "/blog/screeps-spawn-exit-blocked-directions",
    category: "SPAWNING · EXIT DIRECTION DIAGNOSIS",
    title:
      "Screeps Spawn Exit Blocked: Diagnose Directions and Occupied Tiles",
    description:
      "Inspect all eight Spawn-adjacent tiles, separate stable obstacles from temporary occupancy, submit one ordered directions list, refresh it near completion, and verify the Creep's later birth state.",
    publishedAt: "2026-08-06",
    publishedLabel: "August 6, 2026",
    readingTime: "17 min read",
    primaryKeyword: "Screeps Spawn exit blocked",
    searchIntent:
      "Diagnose a scheduled Creep that cannot complete birth because its permitted Spawn-adjacent exit tiles are blocked or temporarily occupied",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Spawn exit blocked",
      "spawnCreep directions",
      "StructureSpawn.Spawning.setDirections",
      "Screeps Creep stuck in Spawn",
      "Screeps Spawn adjacent tiles",
    ],
  },
  {
    href: "/en/blog/screeps-multi-spawn-queue",
    chinesePath: "/blog/screeps-multi-spawn-queue",
    category: "SPAWNING · QUEUE SCHEDULING",
    title:
      "Screeps Multi-Spawn Queue: Priority, Deduplication, and Shared Energy",
    description:
      "Centralize Creep demand, deduplicate stable request keys, rank emergency and replacement work, reserve shared room Energy locally, assign each idle Spawn once, and verify accepted names on later ticks.",
    publishedAt: "2026-08-06",
    publishedLabel: "August 6, 2026",
    readingTime: "20 min read",
    primaryKeyword: "Screeps multi Spawn queue",
    searchIntent:
      "Coordinate multiple Creep requests and idle Spawns without duplicate demand, priority inversion, or same-tick shared Energy overcommitment",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps multi Spawn queue",
      "Screeps Spawn scheduler",
      "Screeps spawn priority",
      "Screeps spawnCreep dryRun shared Energy",
      "Screeps Creep request deduplication",
    ],
  },
  {
    href: "/en/blog/screeps-store-capacity-api",
    chinesePath: "/blog/screeps-store-capacity-api",
    category: "ROOM ECONOMY · STORE CAPACITY",
    title:
      "Screeps Store API: getUsedCapacity, getFreeCapacity, and null",
    description:
      "Distinguish general, limited, and read-only Stores; interpret resource arguments, zero and null correctly; handle Lab and specialized capacities; and calculate safe withdraw and transfer amounts.",
    publishedAt: "2026-08-06",
    publishedLabel: "August 6, 2026",
    readingTime: "18 min read",
    primaryKeyword: "Screeps Store API",
    searchIntent:
      "Interpret Store capacity methods correctly across general, limited, specialized, inactive, and read-only resource objects",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps Store API",
      "Screeps getUsedCapacity",
      "Screeps getFreeCapacity",
      "Screeps getCapacity null",
      "Screeps Lab Store capacity",
    ],
  },
  {
    href: "/en/blog/screeps-intershardmemory-sync",
    chinesePath: "/blog/screeps-intershardmemory-sync",
    category: "MEMORY · CROSS-SHARD STATE",
    title:
      "Screeps InterShardMemory: Versioned Cross-Shard State Without Remote Writes",
    description:
      "Publish versioned shard-owned channels, validate remote strings, enforce a conservative UTF-8 project budget, detect writer restarts and revision regressions, and measure freshness with local observation windows.",
    publishedAt: "2026-08-17",
    publishedLabel: "August 17, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps InterShardMemory",
    searchIntent:
      "Synchronize versioned state across Screeps shards without writing remote data or assuming one shared tick clock",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps InterShardMemory",
      "Screeps cross shard Memory",
      "InterShardMemory getRemote",
      "InterShardMemory setLocal",
      "Screeps shard state synchronization",
    ],
  },
  {
    href: "/en/blog/screeps-rawmemory-foreign-segment",
    chinesePath: "/blog/screeps-rawmemory-foreign-segment",
    category: "MEMORY · PUBLIC FOREIGN SEGMENTS",
    title:
      "Screeps RawMemory Foreign Segment: Publish and Read Public Segments Safely",
    description:
      "Publish versioned public RawMemory segments, request one foreign segment for the next tick, validate untrusted JSON, rotate subscriptions, and detect stream changes without confusing local, cross-shard, and foreign storage.",
    publishedAt: "2026-08-17",
    publishedLabel: "August 17, 2026",
    readingTime: "19 min read",
    primaryKeyword: "Screeps RawMemory foreignSegment",
    searchIntent:
      "Publish or subscribe to one versioned public Screeps memory segment with next-tick matching, safe parsing, and explicit polling",
    status: "published",
    finalScore: 98,
    keywords: [
      "Screeps RawMemory foreignSegment",
      "RawMemory setActiveForeignSegment",
      "Screeps public memory segment",
      "RawMemory setPublicSegments",
      "Screeps foreign segment next tick",
    ],
  },
];