export interface ScreepsApiReferenceEntry {
  id: string;
  group: "Game" | "Creep" | "Room" | "Structures" | "Systems";
  signature: string;
  summary: string;
  keywords: string[];
  guideHref?: string;
}

export const screepsApiReference: ScreepsApiReferenceEntry[] = [
  {
    id: "game-time",
    group: "Game",
    signature: "Game.time",
    summary: "读取当前游戏 tick 编号，用于定时任务、日志和跨 tick 状态判断。",
    keywords: ["tick", "时间", "游戏循环"],
    guideHref: "/blog/screeps-tick-and-game-loop",
  },
  {
    id: "game-rooms",
    group: "Game",
    signature: "Game.rooms[roomName]",
    summary: "读取当前可见房间；房间没有视野时结果可能是 undefined。",
    keywords: ["Room", "视野", "undefined"],
    guideHref: "/blog/screeps-room-visibility",
  },
  {
    id: "game-get-object-by-id",
    group: "Game",
    signature: "Game.getObjectById(id)",
    summary: "通过对象 ID 恢复当前可访问的游戏对象；找不到时返回 null。",
    keywords: ["ID", "Memory", "目标缓存", "null"],
    guideHref: "/blog/screeps-game-get-object-by-id",
  },
  {
    id: "game-notify",
    group: "Game",
    signature: "Game.notify(message, groupInterval)",
    summary: "安排账号通知，适合 Controller 风险、断代和其他需要离开 Console 后继续关注的事件。",
    keywords: ["通知", "告警", "groupInterval"],
    guideHref: "/blog/screeps-game-notify",
  },
  {
    id: "game-cpu-get-used",
    group: "Game",
    signature: "Game.cpu.getUsed()",
    summary: "读取当前 tick 到调用位置已经消耗的 CPU，可用前后差值测量代码段。",
    keywords: ["CPU", "bucket", "性能"],
    guideHref: "/blog/screeps-cpu-getused-bucket",
  },
  {
    id: "game-map-find-route",
    group: "Game",
    signature: "Game.map.findRoute(from, to, opts)",
    summary: "规划房间级跨房路线，返回出口方向和下一房间序列。",
    keywords: ["跨房间", "路线", "routeCallback"],
    guideHref: "/blog/screeps-map-find-route",
  },
  {
    id: "creep-move-to",
    group: "Creep",
    signature: "creep.moveTo(target, opts)",
    summary: "为 Creep 安排移动；返回 OK 只表示移动命令被接受，不代表当前位置已经改变。",
    keywords: ["移动", "ERR_NO_PATH", "fatigue", "路径"],
    guideHref: "/blog/screeps-moveto-not-moving",
  },
  {
    id: "creep-harvest",
    group: "Creep",
    signature: "creep.harvest(target)",
    summary: "从 Source、Mineral 等允许的资源对象采集资源，需要对应有效身体部件。",
    keywords: ["Source", "Energy", "WORK", "采集"],
    guideHref: "/blog/screeps-first-creep-harvest",
  },
  {
    id: "creep-transfer",
    group: "Creep",
    signature: "creep.transfer(target, resourceType, amount?)",
    summary: "把 Creep Store 中的资源转移给可接收目标。",
    keywords: ["运输", "Energy", "Store", "Spawn"],
    guideHref: "/blog/screeps-creep-deliver-energy",
  },
  {
    id: "creep-withdraw",
    group: "Creep",
    signature: "creep.withdraw(target, resourceType, amount?)",
    summary: "从 Structure、Tombstone 或 Ruin 的 Store 中取出资源。",
    keywords: ["Container", "Storage", "Store", "取能"],
    guideHref: "/blog/screeps-creep-withdraw-container-energy",
  },
  {
    id: "creep-pickup",
    group: "Creep",
    signature: "creep.pickup(resource)",
    summary: "拾取地面 Resource 对象；Container 等 Store 目标应使用 withdraw。",
    keywords: ["掉落资源", "Energy", "Resource"],
    guideHref: "/blog/screeps-creep-pickup-dropped-energy",
  },
  {
    id: "creep-upgrade-controller",
    group: "Creep",
    signature: "creep.upgradeController(controller)",
    summary: "消耗 Creep 携带的 Energy 提升己方 Controller 进度。",
    keywords: ["Controller", "升级", "WORK", "Upgrader"],
    guideHref: "/blog/screeps-upgrade-controller",
  },
  {
    id: "creep-build",
    group: "Creep",
    signature: "creep.build(target)",
    summary: "消耗 Creep 携带的 Energy 推进 Construction Site 建造进度，需要有效 WORK 部件并满足动作距离。",
    keywords: ["Builder", "Construction Site", "WORK", "Energy", "建造"],
    guideHref: "/blog/screeps-build-and-repair",
  },
  {
    id: "creep-repair",
    group: "Creep",
    signature: "creep.repair(target)",
    summary: "消耗 Creep 携带的 Energy 修复可维修结构，需要有效 WORK 部件并满足动作距离。",
    keywords: ["Builder", "repair", "WORK", "Energy", "维修"],
    guideHref: "/blog/screeps-build-and-repair",
  },
  {
    id: "room-create-construction-site",
    group: "Room",
    signature: "room.createConstructionSite(x, y, structureType)",
    summary: "在指定坐标提交 Construction Site 创建请求，正式结果以返回码为准。",
    keywords: ["Construction Site", "建造", "Road"],
    guideHref: "/blog/screeps-room-create-construction-site",
  },
  {
    id: "room-get-event-log",
    group: "Room",
    signature: "room.getEventLog(raw?)",
    summary: "读取上一 tick 的房间事件，可用于攻击、维修、建造等行为的后续验证。",
    keywords: ["事件日志", "event", "上一 tick"],
    guideHref: "/blog/screeps-room-event-log",
  },
  {
    id: "spawn-spawn-creep",
    group: "Structures",
    signature: "spawn.spawnCreep(body, name, opts?)",
    summary: "提交 Creep 生成请求；建议保存 dryRun 和正式返回值并检查名称、身体与 Energy。",
    keywords: ["Spawn", "Creep", "body", "dryRun"],
    guideHref: "/blog/screeps-spawncreep-return-codes",
  },
  {
    id: "spawn-renew-creep",
    group: "Structures",
    signature: "spawn.renewCreep(creep)",
    summary: "使用 Spawn 为符合条件的普通 Creep 增加寿命，同时需要评估 Spawn 占用和 Boost 边界。",
    keywords: ["Spawn", "TTL", "ticksToLive", "续命"],
    guideHref: "/blog/screeps-spawn-renew-creep",
  },
  {
    id: "spawn-recycle-creep",
    group: "Structures",
    signature: "spawn.recycleCreep(creep)",
    summary: "回收不再需要的 Creep；目标需要靠近己方 Spawn，并应作为明确的一次性任务执行。",
    keywords: ["Spawn", "Creep", "回收"],
    guideHref: "/blog/screeps-spawn-recycle-creep",
  },
  {
    id: "link-transfer-energy",
    group: "Structures",
    signature: "link.transferEnergy(target, amount?)",
    summary: "在同一房间的 Link 之间传输 Energy，需要检查 cooldown、库存、容量与传输损耗。",
    keywords: ["Link", "Energy", "cooldown", "物流"],
    guideHref: "/blog/screeps-link-transfer-energy",
  },
  {
    id: "tower-attack-heal-repair",
    group: "Structures",
    signature: "tower.attack() / heal() / repair()",
    summary: "Tower 的三类主要动作共享每 tick 的行动机会，效果会受到距离和 Power 效果影响。",
    keywords: ["Tower", "攻击", "治疗", "维修"],
    guideHref: "/tools/tower-damage-heal-repair-calculator",
  },
  {
    id: "terminal-send",
    group: "Structures",
    signature: "terminal.send(resourceType, amount, destination, description?)",
    summary: "跨房间发送资源，并由发送方承担交易 Energy；需要检查 cooldown、库存和目标房间。",
    keywords: ["Terminal", "跨房间", "Energy", "物流"],
    guideHref: "/blog/screeps-terminal-send-resources",
  },
  {
    id: "lab-run-reaction",
    group: "Structures",
    signature: "lab.runReaction(inputLab1, inputLab2)",
    summary: "让输出 Lab 消耗两座输入 Lab 的矿物并生成化合物。",
    keywords: ["Lab", "矿物反应", "REACTIONS"],
    guideHref: "/blog/screeps-lab-run-reaction",
  },
  {
    id: "lab-boost-creep",
    group: "Structures",
    signature: "lab.boostCreep(creep, bodyPartsCount?)",
    summary: "使用 Lab 中的化合物和 Energy 强化匹配的 Creep 身体部件。",
    keywords: ["Lab", "Boost", "bodyPartsCount"],
    guideHref: "/blog/screeps-lab-boost-creep",
  },
  {
    id: "factory-produce",
    group: "Structures",
    signature: "factory.produce(resourceType)",
    summary: "根据 COMMODITIES 配方安排商品生产，需要检查组件、容量、等级和 cooldown。",
    keywords: ["Factory", "COMMODITIES", "商品"],
    guideHref: "/blog/screeps-factory-produce",
  },
  {
    id: "observer-observe-room",
    group: "Structures",
    signature: "observer.observeRoom(roomName)",
    summary: "提交远方房间观察请求；目标 Room 应在后续 tick 再从 Game.rooms 读取。",
    keywords: ["Observer", "视野", "跨房间"],
    guideHref: "/blog/screeps-observer-observe-room",
  },
  {
    id: "market-deal",
    group: "Systems",
    signature: "Game.market.deal(orderId, amount, roomName?)",
    summary: "对指定市场订单执行真实成交，需要同时检查订单状态、Credits、资源和 Terminal 交易成本。",
    keywords: ["Market", "deal", "订单", "Credits"],
    guideHref: "/blog/screeps-market-deal",
  },
  {
    id: "market-create-order",
    group: "Systems",
    signature: "Game.market.createOrder(params)",
    summary: "创建自己的市场买单或卖单，并支付创建订单费用。",
    keywords: ["Market", "订单", "createOrder"],
    guideHref: "/blog/screeps-market-create-order",
  },
  {
    id: "pathfinder-search",
    group: "Systems",
    signature: "PathFinder.search(origin, goal, opts?)",
    summary: "执行格子级路径搜索；应同时检查 path、cost、ops 和 incomplete。",
    keywords: ["PathFinder", "CostMatrix", "寻路", "incomplete"],
    guideHref: "/blog/screeps-pathfinder-costmatrix",
  },
];

export const screepsApiGroups = ["Game", "Creep", "Room", "Structures", "Systems"] as const;
