-- linqingan.com platform data foundation
-- Applied to Neon project linqingan-platform on 2026-08-10.
-- Markdown content remains the source of truth; these tables store search and platform events only.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS search_documents (
  id text PRIMARY KEY,
  type text NOT NULL,
  language text NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  href text NOT NULL,
  module text,
  keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
  headings jsonb NOT NULL DEFAULT '[]'::jsonb,
  search_text text NOT NULL DEFAULT '',
  source_updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS search_documents_language_href_uidx ON search_documents(language, href);
CREATE INDEX IF NOT EXISTS search_documents_type_language_idx ON search_documents(type, language);
CREATE INDEX IF NOT EXISTS search_documents_title_trgm_idx ON search_documents USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS search_documents_search_text_trgm_idx ON search_documents USING gin (search_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS search_documents_fts_idx ON search_documents USING gin (to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(search_text,'')));

CREATE TABLE IF NOT EXISTS search_queries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_id text,
  session_id text,
  language text NOT NULL,
  query text NOT NULL,
  normalized_query text NOT NULL,
  result_count integer NOT NULL DEFAULT 0,
  source_path text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS search_queries_created_at_idx ON search_queries(created_at DESC);
CREATE INDEX IF NOT EXISTS search_queries_zero_result_idx ON search_queries(created_at DESC) WHERE result_count = 0;
CREATE INDEX IF NOT EXISTS search_queries_normalized_trgm_idx ON search_queries USING gin (normalized_query gin_trgm_ops);

CREATE TABLE IF NOT EXISTS search_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_query_id bigint REFERENCES search_queries(id) ON DELETE SET NULL,
  anonymous_id text,
  session_id text,
  query text NOT NULL,
  result_id text,
  result_type text,
  result_href text NOT NULL,
  position integer,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS search_clicks_created_at_idx ON search_clicks(created_at DESC);
CREATE INDEX IF NOT EXISTS search_clicks_result_href_idx ON search_clicks(result_href);

CREATE TABLE IF NOT EXISTS article_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_slug text NOT NULL,
  language text NOT NULL,
  helpful boolean NOT NULL,
  reason text,
  anonymous_id text,
  session_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS article_feedback_article_idx ON article_feedback(article_slug, language, created_at DESC);

CREATE TABLE IF NOT EXISTS tool_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id text NOT NULL,
  action text NOT NULL,
  source_path text,
  anonymous_id text,
  session_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tool_events_tool_created_idx ON tool_events(tool_id, created_at DESC);

CREATE TABLE IF NOT EXISTS verification_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_slug text NOT NULL,
  language text NOT NULL DEFAULT 'zh-CN',
  verification_type text NOT NULL,
  game_time bigint,
  shard text,
  room_name text,
  api_name text,
  return_code text,
  before_state jsonb,
  after_state jsonb,
  tick_start bigint,
  tick_end bigint,
  evidence_note text,
  source_ref text,
  verified_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_evidence_article_idx ON verification_evidence(article_slug, verified_at DESC);
CREATE INDEX IF NOT EXISTS verification_evidence_type_idx ON verification_evidence(verification_type, verified_at DESC);
