-- Resolver Observability Batch 01.
-- Development migration only. Do not apply to Production without explicit release authorization.
-- Stores structured Resolver interaction IDs only; no free text, IP, Referer, User-Agent, or Runtime Evidence payloads.

CREATE TABLE IF NOT EXISTS public.resolver_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_id text,
  session_id text,
  language text NOT NULL,
  event_name text NOT NULL,
  flow_id text NOT NULL,
  step_id text,
  option_id text,
  outcome_id text,
  target_id text,
  target_kind text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT resolver_events_language_check
    CHECK (language IN ('zh', 'en')),
  CONSTRAINT resolver_events_event_name_check
    CHECK (
      event_name IN (
        'flow_started',
        'step_answered',
        'outcome_reached',
        'diagnostics_clicked',
        'guide_clicked',
        'tool_clicked',
        'ticklab_clicked'
      )
    ),
  CONSTRAINT resolver_events_target_kind_check
    CHECK (
      target_kind IS NULL OR
      target_kind IN ('diagnostics', 'guide', 'api', 'tool', 'ticklab')
    )
);

CREATE INDEX IF NOT EXISTS resolver_events_created_at_idx
  ON public.resolver_events(created_at DESC);

CREATE INDEX IF NOT EXISTS resolver_events_event_created_idx
  ON public.resolver_events(event_name, created_at DESC);

CREATE INDEX IF NOT EXISTS resolver_events_flow_created_idx
  ON public.resolver_events(flow_id, created_at DESC);

CREATE INDEX IF NOT EXISTS resolver_events_outcome_created_idx
  ON public.resolver_events(outcome_id, created_at DESC)
  WHERE outcome_id IS NOT NULL;
