-- Canonical production schema baseline captured from linqingan-platform/neondb on 2026-08-20.
-- PostgreSQL 18.6. Schema only: no row data, secrets, roles, or environment-specific connection details.
-- This file represents production before migration 0002_site_intelligence_hardening.sql.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE public.search_queries (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  anonymous_id text,
  session_id text,
  language text NOT NULL,
  query text NOT NULL,
  normalized_query text NOT NULL,
  result_count integer DEFAULT 0 NOT NULL,
  source_path text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT search_queries_pkey PRIMARY KEY (id),
  CONSTRAINT search_queries_result_count_nonnegative CHECK (result_count >= 0)
);

CREATE TABLE public.search_documents (
  id text NOT NULL,
  type text NOT NULL,
  language text NOT NULL,
  title text NOT NULL,
  description text DEFAULT ''::text NOT NULL,
  href text NOT NULL,
  module text,
  keywords jsonb DEFAULT '[]'::jsonb NOT NULL,
  headings jsonb DEFAULT '[]'::jsonb NOT NULL,
  search_text text DEFAULT ''::text NOT NULL,
  source_updated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT search_documents_pkey PRIMARY KEY (id)
);

CREATE TABLE public.article_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  article_slug text NOT NULL,
  language text NOT NULL,
  helpful boolean NOT NULL,
  reason text,
  anonymous_id text,
  session_id text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT article_feedback_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tool_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tool_id text NOT NULL,
  action text NOT NULL,
  source_path text,
  anonymous_id text,
  session_id text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT tool_events_pkey PRIMARY KEY (id)
);

CREATE TABLE public.verification_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  article_slug text NOT NULL,
  language text DEFAULT 'zh-CN'::text NOT NULL,
  verification_type text NOT NULL,
  game_time bigint,
  shard text,
  room_name text,
  api_name text NOT NULL,
  return_code text,
  before_state jsonb,
  after_state jsonb,
  tick_start bigint,
  tick_end bigint,
  evidence_note text NOT NULL,
  source_ref text NOT NULL,
  verified_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  evidence_key text NOT NULL,
  status text DEFAULT 'captured'::text NOT NULL,
  reviewed_at timestamp with time zone,
  review_note text,
  accepted_at timestamp with time zone,
  revoked_at timestamp with time zone,
  revoked_reason text,
  CONSTRAINT verification_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT verification_evidence_status_check CHECK (status = ANY (ARRAY['captured'::text, 'reviewed'::text, 'accepted'::text, 'rejected'::text, 'revoked'::text]))
);

CREATE TABLE public.site_intelligence_actions (
  action_id text NOT NULL,
  asset_id text,
  path text,
  category text NOT NULL,
  recommended_action text NOT NULL,
  priority text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  review_after timestamp with time zone,
  action_taken text,
  rejection_reason text,
  before_metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
  after_metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
  result text,
  source_signal_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  due_at timestamp with time zone,
  parent_action_id text,
  superseded_by_action_id text,
  CONSTRAINT site_intelligence_actions_priority_check CHECK (priority = ANY (ARRAY['P0'::text, 'P1'::text, 'P2'::text])),
  CONSTRAINT site_intelligence_actions_status_check CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'done'::text, 'rejected'::text, 'superseded'::text])),
  CONSTRAINT site_intelligence_actions_result_check CHECK (result IS NULL OR (result = ANY (ARRAY['improved'::text, 'neutral'::text, 'declined'::text, 'mixed'::text]))),
  CONSTRAINT site_intelligence_actions_pkey PRIMARY KEY (action_id),
  CONSTRAINT site_intelligence_actions_parent_action_id_fkey FOREIGN KEY (parent_action_id) REFERENCES site_intelligence_actions(action_id) ON DELETE SET NULL,
  CONSTRAINT site_intelligence_actions_superseded_by_action_id_fkey FOREIGN KEY (superseded_by_action_id) REFERENCES site_intelligence_actions(action_id) ON DELETE SET NULL,
  CONSTRAINT site_intelligence_actions_parent_not_self CHECK (parent_action_id IS NULL OR parent_action_id <> action_id),
  CONSTRAINT site_intelligence_actions_superseded_not_self CHECK (superseded_by_action_id IS NULL OR superseded_by_action_id <> action_id)
);

CREATE TABLE public.site_intelligence_import_runs (
  import_id text NOT NULL,
  source text NOT NULL,
  source_label text,
  original_filename text,
  period_start date,
  period_end date,
  status text NOT NULL,
  input_fingerprint text,
  rows_received integer DEFAULT 0 NOT NULL,
  rows_accepted integer DEFAULT 0 NOT NULL,
  rows_rejected integer DEFAULT 0 NOT NULL,
  rows_unmapped integer DEFAULT 0 NOT NULL,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  completed_at timestamp with time zone,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT site_intelligence_import_runs_status_check CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'partial'::text, 'failed'::text])),
  CONSTRAINT site_intelligence_import_runs_rows_received_check CHECK (rows_received >= 0),
  CONSTRAINT site_intelligence_import_runs_rows_accepted_check CHECK (rows_accepted >= 0),
  CONSTRAINT site_intelligence_import_runs_rows_rejected_check CHECK (rows_rejected >= 0),
  CONSTRAINT site_intelligence_import_runs_rows_unmapped_check CHECK (rows_unmapped >= 0),
  CONSTRAINT site_intelligence_import_runs_check CHECK (period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
  CONSTRAINT site_intelligence_import_runs_check1 CHECK ((rows_accepted + rows_rejected) <= rows_received),
  CONSTRAINT site_intelligence_import_runs_check2 CHECK (rows_unmapped <= rows_received),
  CONSTRAINT site_intelligence_import_runs_pkey PRIMARY KEY (import_id)
);
