-- Continuation of the 2026-08-20 production schema baseline.

CREATE TABLE public.search_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  search_query_id bigint,
  anonymous_id text,
  session_id text,
  query text NOT NULL,
  result_id text,
  result_type text,
  result_href text NOT NULL,
  "position" integer,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT search_clicks_pkey PRIMARY KEY (id),
  CONSTRAINT search_clicks_search_query_id_fkey FOREIGN KEY (search_query_id) REFERENCES search_queries(id) ON DELETE SET NULL,
  CONSTRAINT search_clicks_position_nonnegative CHECK ("position" >= 0)
);

CREATE TABLE public.site_intelligence_action_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  action_id text NOT NULL,
  event_type text NOT NULL,
  from_status text,
  to_status text,
  note text,
  metrics jsonb DEFAULT '{}'::jsonb NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT site_intelligence_action_events_pkey PRIMARY KEY (id),
  CONSTRAINT site_intelligence_action_events_action_id_fkey FOREIGN KEY (action_id) REFERENCES site_intelligence_actions(action_id) ON DELETE CASCADE,
  CONSTRAINT site_intelligence_action_events_event_type_check CHECK (event_type = ANY (ARRAY['created'::text, 'seen'::text, 'status_change'::text, 'note'::text, 'before_snapshot'::text, 'after_snapshot'::text, 'review'::text, 'due_date_change'::text, 'relationship_change'::text, 'reopened'::text]))
);

CREATE TABLE public.site_intelligence_action_links (
  from_action_id text NOT NULL,
  relationship_type text NOT NULL,
  to_action_id text NOT NULL,
  note text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT site_intelligence_action_links_relationship_type_check CHECK (relationship_type = ANY (ARRAY['related'::text, 'blocks'::text, 'duplicate_of'::text, 'follow_up'::text])),
  CONSTRAINT site_intelligence_action_links_check CHECK (from_action_id <> to_action_id),
  CONSTRAINT site_intelligence_action_links_pkey PRIMARY KEY (from_action_id, relationship_type, to_action_id),
  CONSTRAINT site_intelligence_action_links_from_action_id_fkey FOREIGN KEY (from_action_id) REFERENCES site_intelligence_actions(action_id) ON DELETE CASCADE,
  CONSTRAINT site_intelligence_action_links_to_action_id_fkey FOREIGN KEY (to_action_id) REFERENCES site_intelligence_actions(action_id) ON DELETE CASCADE
);

CREATE TABLE public.site_intelligence_data_quality_issues (
  issue_id text NOT NULL,
  issue_type text NOT NULL,
  severity text DEFAULT 'warning'::text NOT NULL,
  status text DEFAULT 'open'::text NOT NULL,
  source text NOT NULL,
  asset_id text,
  entity_kind text,
  entity_key text,
  issue_fingerprint text NOT NULL,
  first_import_id text,
  last_import_id text,
  occurrence_count integer DEFAULT 1 NOT NULL,
  first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  resolution text,
  resolved_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT site_intelligence_data_quality_issues_issue_type_check CHECK (issue_type = ANY (ARRAY['unknown_url'::text, 'missing_asset'::text, 'unknown_keyword_owner'::text, 'unknown_tool_id'::text, 'unknown_article_slug'::text, 'duplicate_asset'::text, 'ambiguous_owner'::text, 'stale_canonical'::text, 'missing_relationship'::text, 'invalid_row'::text, 'other'::text])),
  CONSTRAINT site_intelligence_data_quality_issues_severity_check CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'error'::text])),
  CONSTRAINT site_intelligence_data_quality_issues_status_check CHECK (status = ANY (ARRAY['open'::text, 'resolved'::text, 'ignored'::text])),
  CONSTRAINT site_intelligence_data_quality_issues_occurrence_count_check CHECK (occurrence_count >= 1),
  CONSTRAINT site_intelligence_data_quality_issues_pkey PRIMARY KEY (issue_id),
  CONSTRAINT site_intelligence_data_quality_issues_issue_fingerprint_key UNIQUE (issue_fingerprint),
  CONSTRAINT site_intelligence_data_quality_issues_first_import_id_fkey FOREIGN KEY (first_import_id) REFERENCES site_intelligence_import_runs(import_id) ON DELETE SET NULL,
  CONSTRAINT site_intelligence_data_quality_issues_last_import_id_fkey FOREIGN KEY (last_import_id) REFERENCES site_intelligence_import_runs(import_id) ON DELETE SET NULL
);

CREATE TABLE public.site_intelligence_gsc_observations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  source_import_id text NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  page_path text NOT NULL,
  query text DEFAULT ''::text NOT NULL,
  asset_id text,
  owner_keyword text,
  owner_asset_id text,
  owner_status text DEFAULT 'not_evaluated'::text NOT NULL,
  clicks bigint DEFAULT 0 NOT NULL,
  impressions bigint DEFAULT 0 NOT NULL,
  ctr numeric(12,8) DEFAULT 0 NOT NULL,
  "position" numeric(12,4),
  row_fingerprint text NOT NULL,
  captured_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  CONSTRAINT site_intelligence_gsc_observations_owner_status_check CHECK (owner_status = ANY (ARRAY['matched'::text, 'mismatch'::text, 'unowned'::text, 'unmapped'::text, 'not_evaluated'::text])),
  CONSTRAINT site_intelligence_gsc_observations_clicks_check CHECK (clicks >= 0),
  CONSTRAINT site_intelligence_gsc_observations_impressions_check CHECK (impressions >= 0),
  CONSTRAINT site_intelligence_gsc_observations_ctr_check CHECK (ctr >= 0::numeric),
  CONSTRAINT site_intelligence_gsc_observations_position_check CHECK ("position" IS NULL OR "position" >= 0::numeric),
  CONSTRAINT site_intelligence_gsc_observations_check CHECK (period_end >= period_start),
  CONSTRAINT site_intelligence_gsc_observations_pkey PRIMARY KEY (id),
  CONSTRAINT site_intelligence_gsc_observa_period_start_period_end_page__key UNIQUE (period_start, period_end, page_path, query),
  CONSTRAINT site_intelligence_gsc_observations_source_import_id_fkey FOREIGN KEY (source_import_id) REFERENCES site_intelligence_import_runs(import_id) ON DELETE RESTRICT
);

CREATE TABLE public.site_intelligence_relationships (
  relationship_id text NOT NULL,
  from_kind text NOT NULL,
  from_key text NOT NULL,
  relationship_type text NOT NULL,
  to_kind text NOT NULL,
  to_key text NOT NULL,
  basis text NOT NULL,
  source_import_id text,
  status text DEFAULT 'active'::text NOT NULL,
  first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT site_intelligence_relationships_from_kind_check CHECK (from_kind = ANY (ARRAY['asset'::text, 'keyword'::text, 'path'::text])),
  CONSTRAINT site_intelligence_relationships_relationship_type_check CHECK (relationship_type = ANY (ARRAY['belongs_to'::text, 'references'::text, 'solves'::text, 'supports'::text, 'has_evidence'::text, 'owned_by'::text, 'related_to'::text, 'canonical_to'::text, 'redirects_to'::text, 'replaces'::text])),
  CONSTRAINT site_intelligence_relationships_to_kind_check CHECK (to_kind = ANY (ARRAY['asset'::text, 'keyword'::text, 'path'::text])),
  CONSTRAINT site_intelligence_relationships_basis_check CHECK (basis = ANY (ARRAY['metadata'::text, 'registry'::text, 'content_link'::text, 'keyword_owner'::text, 'runtime_evidence'::text, 'manual'::text])),
  CONSTRAINT site_intelligence_relationships_status_check CHECK (status = ANY (ARRAY['active'::text, 'stale'::text, 'rejected'::text])),
  CONSTRAINT site_intelligence_relationships_check CHECK (NOT (from_kind = to_kind AND from_key = to_key)),
  CONSTRAINT site_intelligence_relationships_pkey PRIMARY KEY (relationship_id),
  CONSTRAINT site_intelligence_relationshi_from_kind_from_key_relationsh_key UNIQUE (from_kind, from_key, relationship_type, to_kind, to_key),
  CONSTRAINT site_intelligence_relationships_source_import_id_fkey FOREIGN KEY (source_import_id) REFERENCES site_intelligence_import_runs(import_id) ON DELETE SET NULL
);

CREATE TABLE public.site_intelligence_snapshots (
  snapshot_id text NOT NULL,
  snapshot_type text NOT NULL,
  generated_at timestamp with time zone NOT NULL,
  source_generated_at timestamp with time zone,
  window_days integer,
  summary jsonb DEFAULT '{}'::jsonb NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb NOT NULL,
  input_fingerprint text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT site_intelligence_snapshots_snapshot_type_check CHECK (snapshot_type = ANY (ARRAY['signals'::text, 'action_queue'::text])),
  CONSTRAINT site_intelligence_snapshots_window_days_check CHECK (window_days IS NULL OR window_days >= 1 AND window_days <= 365),
  CONSTRAINT site_intelligence_snapshots_pkey PRIMARY KEY (snapshot_id)
);
